// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/infraestructure/http/grpc/oauthpb/oauth.proto

package oauthpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ValidateTokenResponse_UserPayload_Role int32

const (
	ValidateTokenResponse_UserPayload_UNKNOWN ValidateTokenResponse_UserPayload_Role = 0
	ValidateTokenResponse_UserPayload_USER    ValidateTokenResponse_UserPayload_Role = 1
	ValidateTokenResponse_UserPayload_ADMIN   ValidateTokenResponse_UserPayload_Role = 2
)

var ValidateTokenResponse_UserPayload_Role_name = map[int32]string{
	0: "UNKNOWN",
	1: "USER",
	2: "ADMIN",
}

var ValidateTokenResponse_UserPayload_Role_value = map[string]int32{
	"UNKNOWN": 0,
	"USER":    1,
	"ADMIN":   2,
}

func (x ValidateTokenResponse_UserPayload_Role) String() string {
	return proto.EnumName(ValidateTokenResponse_UserPayload_Role_name, int32(x))
}

func (ValidateTokenResponse_UserPayload_Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d66fdbd4a55bbcce, []int{1, 0, 0}
}

type ValidateTokenRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateTokenRequest) Reset()         { *m = ValidateTokenRequest{} }
func (m *ValidateTokenRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateTokenRequest) ProtoMessage()    {}
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66fdbd4a55bbcce, []int{0}
}

func (m *ValidateTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateTokenRequest.Unmarshal(m, b)
}
func (m *ValidateTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateTokenRequest.Marshal(b, m, deterministic)
}
func (m *ValidateTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateTokenRequest.Merge(m, src)
}
func (m *ValidateTokenRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateTokenRequest.Size(m)
}
func (m *ValidateTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateTokenRequest proto.InternalMessageInfo

func (m *ValidateTokenRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type ValidateTokenResponse struct {
	UserPayload          *ValidateTokenResponse_UserPayload `protobuf:"bytes,1,opt,name=user_payload,json=userPayload,proto3" json:"user_payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *ValidateTokenResponse) Reset()         { *m = ValidateTokenResponse{} }
func (m *ValidateTokenResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateTokenResponse) ProtoMessage()    {}
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66fdbd4a55bbcce, []int{1}
}

func (m *ValidateTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateTokenResponse.Unmarshal(m, b)
}
func (m *ValidateTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateTokenResponse.Marshal(b, m, deterministic)
}
func (m *ValidateTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateTokenResponse.Merge(m, src)
}
func (m *ValidateTokenResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateTokenResponse.Size(m)
}
func (m *ValidateTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateTokenResponse proto.InternalMessageInfo

func (m *ValidateTokenResponse) GetUserPayload() *ValidateTokenResponse_UserPayload {
	if m != nil {
		return m.UserPayload
	}
	return nil
}

type ValidateTokenResponse_UserPayload struct {
	UserId               int64                                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role                 ValidateTokenResponse_UserPayload_Role `protobuf:"varint,2,opt,name=role,proto3,enum=oauth.ValidateTokenResponse_UserPayload_Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *ValidateTokenResponse_UserPayload) Reset()         { *m = ValidateTokenResponse_UserPayload{} }
func (m *ValidateTokenResponse_UserPayload) String() string { return proto.CompactTextString(m) }
func (*ValidateTokenResponse_UserPayload) ProtoMessage()    {}
func (*ValidateTokenResponse_UserPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66fdbd4a55bbcce, []int{1, 0}
}

func (m *ValidateTokenResponse_UserPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateTokenResponse_UserPayload.Unmarshal(m, b)
}
func (m *ValidateTokenResponse_UserPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateTokenResponse_UserPayload.Marshal(b, m, deterministic)
}
func (m *ValidateTokenResponse_UserPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateTokenResponse_UserPayload.Merge(m, src)
}
func (m *ValidateTokenResponse_UserPayload) XXX_Size() int {
	return xxx_messageInfo_ValidateTokenResponse_UserPayload.Size(m)
}
func (m *ValidateTokenResponse_UserPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateTokenResponse_UserPayload.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateTokenResponse_UserPayload proto.InternalMessageInfo

func (m *ValidateTokenResponse_UserPayload) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ValidateTokenResponse_UserPayload) GetRole() ValidateTokenResponse_UserPayload_Role {
	if m != nil {
		return m.Role
	}
	return ValidateTokenResponse_UserPayload_UNKNOWN
}

func init() {
	proto.RegisterEnum("oauth.ValidateTokenResponse_UserPayload_Role", ValidateTokenResponse_UserPayload_Role_name, ValidateTokenResponse_UserPayload_Role_value)
	proto.RegisterType((*ValidateTokenRequest)(nil), "oauth.ValidateTokenRequest")
	proto.RegisterType((*ValidateTokenResponse)(nil), "oauth.ValidateTokenResponse")
	proto.RegisterType((*ValidateTokenResponse_UserPayload)(nil), "oauth.ValidateTokenResponse.UserPayload")
}

func init() {
	proto.RegisterFile("pkg/infraestructure/http/grpc/oauthpb/oauth.proto", fileDescriptor_d66fdbd4a55bbcce)
}

var fileDescriptor_d66fdbd4a55bbcce = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcb, 0x4b, 0xc3, 0x40,
	0x10, 0xc6, 0x9b, 0xda, 0x87, 0x9d, 0x54, 0x29, 0x8b, 0x62, 0xa9, 0x1e, 0x6a, 0x4e, 0xb9, 0x98,
	0xd0, 0x7a, 0x12, 0x4f, 0x15, 0x3d, 0x94, 0x6a, 0x2a, 0x5b, 0xab, 0x20, 0x42, 0xd9, 0xa6, 0x63,
	0x1b, 0x1a, 0xba, 0xeb, 0x3e, 0x04, 0xff, 0x0e, 0xff, 0x5b, 0x4f, 0x92, 0x8d, 0xe0, 0x83, 0x22,
	0x3d, 0x0d, 0xdf, 0xec, 0x7c, 0xdf, 0x6f, 0x99, 0x81, 0x8e, 0x58, 0xce, 0xc3, 0x64, 0xf5, 0x2c,
	0x19, 0x2a, 0x2d, 0x4d, 0xac, 0x8d, 0xc4, 0x70, 0xa1, 0xb5, 0x08, 0xe7, 0x52, 0xc4, 0x21, 0x67,
	0x46, 0x2f, 0xc4, 0x34, 0xaf, 0x81, 0x90, 0x5c, 0x73, 0x52, 0xb6, 0xc2, 0x3b, 0x83, 0xbd, 0x7b,
	0x96, 0x26, 0x33, 0xa6, 0xf1, 0x8e, 0x2f, 0x71, 0x45, 0xf1, 0xc5, 0xa0, 0xd2, 0xe4, 0x18, 0xea,
	0x2c, 0x8e, 0x51, 0xa9, 0x89, 0xce, 0xda, 0x4d, 0xa7, 0xed, 0xf8, 0x35, 0xea, 0xe6, 0x3d, 0x3b,
	0xe9, 0x7d, 0x38, 0xb0, 0xff, 0xc7, 0xab, 0x04, 0x5f, 0x29, 0x24, 0x03, 0xa8, 0x1b, 0x85, 0x72,
	0x22, 0xd8, 0x5b, 0xca, 0xd9, 0xcc, 0x9a, 0xdd, 0xae, 0x1f, 0xe4, 0xfc, 0xb5, 0x9e, 0x60, 0xac,
	0x50, 0xde, 0xe6, 0xf3, 0xd4, 0x35, 0xdf, 0xa2, 0xf5, 0xee, 0x80, 0xfb, 0xe3, 0x91, 0x1c, 0x40,
	0xd5, 0x86, 0x27, 0x79, 0xee, 0x16, 0xad, 0x64, 0xb2, 0x3f, 0x23, 0x3d, 0x28, 0x49, 0x9e, 0x62,
	0xb3, 0xd8, 0x76, 0xfc, 0xdd, 0xee, 0xc9, 0xa6, 0xb4, 0x80, 0xf2, 0x14, 0xa9, 0xb5, 0x7a, 0x3e,
	0x94, 0x32, 0x45, 0x5c, 0xa8, 0x8e, 0xa3, 0x41, 0x34, 0x7c, 0x88, 0x1a, 0x05, 0xb2, 0x0d, 0xa5,
	0xf1, 0xe8, 0x8a, 0x36, 0x1c, 0x52, 0x83, 0x72, 0xef, 0xf2, 0xa6, 0x1f, 0x35, 0x8a, 0xdd, 0x27,
	0xa8, 0x0f, 0xb3, 0xfc, 0x11, 0xca, 0xd7, 0x24, 0x46, 0x72, 0x0d, 0x3b, 0xbf, 0x48, 0xe4, 0x70,
	0x3d, 0xdf, 0x6e, 0xb7, 0x75, 0xf4, 0xdf, 0xe7, 0xbc, 0xc2, 0x45, 0xe7, 0x31, 0x0c, 0xc2, 0x8d,
	0x6e, 0x7a, 0xfe, 0x55, 0xa7, 0x15, 0x7b, 0xd6, 0xd3, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbe,
	0xbe, 0xd0, 0x7f, 0x0b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OauthServiceClient is the client API for OauthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OauthServiceClient interface {
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
}

type oauthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOauthServiceClient(cc grpc.ClientConnInterface) OauthServiceClient {
	return &oauthServiceClient{cc}
}

func (c *oauthServiceClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, "/oauth.OauthService/ValidateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OauthServiceServer is the server API for OauthService service.
type OauthServiceServer interface {
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
}

// UnimplementedOauthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOauthServiceServer struct {
}

func (*UnimplementedOauthServiceServer) ValidateToken(ctx context.Context, req *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}

func RegisterOauthServiceServer(s *grpc.Server, srv OauthServiceServer) {
	s.RegisterService(&_OauthService_serviceDesc, srv)
}

func _OauthService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OauthServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oauth.OauthService/ValidateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OauthServiceServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OauthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oauth.OauthService",
	HandlerType: (*OauthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateToken",
			Handler:    _OauthService_ValidateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/infraestructure/http/grpc/oauthpb/oauth.proto",
}
